# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.

name: Pull Request Labeler
on: 
  - pull_request_target
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yaml
        sync-labels: true
        
